### ISSUE TITLE
创建LINSTOR资源并将资源自动放置，应打印报错的详细信息

### ISSUE THREAD

**Issue by Fredericwu** [FeixiDev/VersaTEL_G2_Code#3]
**Describe the bug**
创建LINSTOR资源并将资源自动放置命令，应打印报错的详细信息

**操作流程**

1. 使用VersaTEL G2工具创建LINSTOR资源并将资源自动放置，操作流程如下:

- python3 vtel.py stor resource c frog -s 30G -a -num 1 
#报错信息为：FAIL

![Screen Shot 2020-05-26 at 4 40 34 PM](https://user-images.githubusercontent.com/41657047/82879556-a8c6ab80-9f6f-11ea-840a-d42330fb0952.png)

2.使用原LINSTOR命令创建LINSTOR资源并将资源自动放置，操作流程如下:

- linstor resource-definition create frog

- linstor volume-definition create frog 30G 

- linstor resource create frog --auto-place 1 
#报错信息为：Error: Socket timeout, no data received for more than 300s.

![Screen Shot 2020-05-26 at 4 13 45 PM](https://user-images.githubusercontent.com/41657047/82879580-b11ee680-9f6f-11ea-87c8-4c6c9bfe18b3.png)

**建议**
捕获原LINSTOR命令创建LINSTOR资源并将资源自动放置的报错信息，VersaTEL G2工具的报错信息只显示FAIL，会让用户操作产生疑惑，无法获知是什么原因导致创建资源失败。

**Submit by Frederic**

**Comment by mattie-feng** [comment]
这应该是个Feature request
